g++ -c font1.cpp
g++ -c   highscores.cpp
g++ -c  physics.cpp
g++ -c    screenscore.cpp
g++ -c vector3f.cpp
g++ -c font.cpp
g++ -c    main.cpp
g++ -c         readData.cpp
g++ -c   terrain.cpp
g++ -c glm.cpp
g++ -c     Obst.cpp
g++ -c scores.cpp
g++ -c texture.cpp
